### ISSUE TITLE
show selected item in breadcrumb

### ISSUE THREAD

**Issue by qlp** [unionlabs/union#2686]
**[Link to user request](https://matrix.to/#/!yhBVbxWoAlhWbXdJjT:goblin.sh/$XB5vbmYnLu_3vgqHDFXBVdv2I67KOF_Lc86kHagxlNw?via=goblin.sh)**

show the address and transfer hash in the breadcrumb:

(replace 'address' with 'address <hash>')
![image](https://github.com/user-attachments/assets/24d79186-2741-4be1-a10b-9b0582a857ac)

(replace 'transfers' with 'transfer <hash>', we can remove the 'transfer <hash> heading in the details panel')
![image](https://github.com/user-attachments/assets/8a64ea28-f1cb-48c1-b1ae-0815f67b1421)

**Comment by cor** [comment]
Done, this is now in production
