### ISSUE TITLE
Voyager internal state caching

### ISSUE THREAD

**Issue by benluelo** [unionlabs/union#2768]
with the new voyager v2 design, modules are fully separated. this leads to lots of requests being duplicated (for example, fetching a channel multiple times in a row at the same height). we should investigate holding an internal "cache" of these values, such that if we request the same (state, height, chain), we can save potentially many rpc requests.

this could potentially also be extended to plugin fetch messages, handle_fetch could return information on if the request is idempotent (i.e. can be infinitely cached).

**Comment by KaiserKarel** [comment]
Alternatively you could make the operator of voyager manage the cache in whatever way (eRPC, generic http request cache)

**Comment by benluelo** [comment]
another potential solution: https://docs.rs/moka/latest/moka/future/struct.Cache.html#method.try_get_with

**Comment by benluelo** [comment]
this was implemented in #2661

the design we went with only caches one type of data - IBC state. since all IBC state voyager works with is assumed to be finalized, we can safely cache the tuple of [`(ChainId<'static>, Path, Height)`](https://github.com/unionlabs/union/blob/main/lib/voyager-message/src/rpc/server.rs#L41), potentially saving multiple calls to multiple different plugins (fetch raw value & decode).

this design works alongside using external caches, as well as with any caching plugins may do (we [cache the client type of wasm blobs](https://github.com/unionlabs/union/blob/86265eb82991586ec571b2540613589216c48a13/voyager/modules/chain/cosmos-sdk/src/main.rs#L88) in the cosmos-sdk chain module, for example).
