### ISSUE TITLE
implement JsonSchema for all hash types in unionlabs

### ISSUE THREAD

**Issue by benluelo** [unionlabs/union#2795]
since we can't derive it due to limitations with how JsonSchema is implemented for arrays, we'll have to implement it manually in the `hex_string_array_wrapper` macro.

**Comment by hussein-aitlahcen** [comment]
Once this is ready, we'll be able to use `H256` directly in cosmwasm execute messages.

**Comment by benluelo** [comment]
after #2984, `JsonSchema` will need to be implemented for `Hash`

**Comment by benluelo** [comment]
completed in https://github.com/unionlabs/union/pull/2984
