### ISSUE TITLE
Explorer wallet connection is not properly styled

### ISSUE THREAD

**Issue by cor** [unionlabs/union#2849]
**Describe the bug**
<img width="624" alt="image" src="https://github.com/user-attachments/assets/3f6afb62-7b8f-42c6-a3ae-965f3e6136f9">
**To Reproduce**
1. Go to explorer.testnet-8.union.build
2. Click on connect wallet

**Expected behavior**
legibility 

**Screenshots**

**Device (please complete the following information):**
 - Hardware: MacBook Pro
 - OS: macOS
 - Browser: Arc

**Comment by Swepool** [comment]
https://github.com/unionlabs/explorer/pull/7
